[Groups.name]
isDefault = false
perms = [
    "perm.one",
    "perm.two.two.six",
    "perm.three.one",
    "perm.four.*"
    ]
extend = [
"Default"
]

[Groups.Default]
isDefault = true
perms = [
    "perm.one",
    "perm.two.two.six",
    "perm.three.one",
    "perm.four.default"
]
extend = [
    "Default"
]

[Groups.Admin]
isDefault = false
perms = [
    "perm.*"
]
extend = [
    "Default"
]

[Groups.Owner]
isDefault = false
perms = [
    "*"
]
extend = [
    "Default"
]
