name: 自动发布

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: maven
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Node.js dependencies
        run: npm install
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get version
        run: node ./javascript/getversion.js

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: github.ref_name == 'master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "exp"
          prerelease: true
          title: "DodoOpenJava${{ steps.Get-version.outputs.version}}"