name: 自动发布

on:
  push:
    branches: [ "release" ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: maven
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Node.js dependencies
        run: npm install
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get Version
        run: |
          node ./js/getversion.js
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: "${{ env.version }}"
          message: "Release version"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Automatic Releases
        run: node ./js/release.js
        env:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          release_title: "DodoOpenJava-${{ env.version }}"
          version: "${{ env.version }}"